"""Deterministic, offline provider used when no LLM API key is configured.

It performs real extractive text-processing (no network calls, no canned
strings) so the app is fully runnable and testable without external
dependencies. It is intentionally NOT a substitute for a real LLM's
reasoning quality -- swap LLM_PROVIDER=openai (or add another provider) for
production-quality generation.
"""

import hashlib
import re
from typing import Any

from app.services.llm.base import EmbeddingResult, LLMProvider, LLMResult, StructuredResult

_STOPWORDS = {
    "the", "a", "an", "of", "in", "on", "and", "or", "to", "is", "are", "for",
    "with", "that", "this", "as", "by", "at", "from", "be", "was", "were",
    "it", "we", "our", "their", "these", "those", "which", "using", "such",
    "can", "than", "into", "also", "have", "has", "had", "not", "but",
}


def _sentences(text: str) -> list[str]:
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text.strip()) if len(s.strip()) > 20]


def _keywords(text: str) -> set[str]:
    words = re.findall(r"[a-zA-Z]{3,}", text.lower())
    return {w for w in words if w not in _STOPWORDS}


def _score_sentence(sentence: str, query_keywords: set[str]) -> int:
    return len(_keywords(sentence) & query_keywords)


class MockLLMProvider(LLMProvider):
    """Extractive summarization + keyword-overlap QA. Deterministic, no network."""

    name = "mock"

    def __init__(self, embedding_dim: int = 384):
        self.embedding_dim = embedding_dim

    def generate(self, system_prompt: str, user_prompt: str, *, temperature: float = 0.2) -> LLMResult:
        sentences = _sentences(user_prompt)
        if not sentences:
            text = "No content was available to analyze."
        else:
            query_kw = _keywords(user_prompt[-400:])
            ranked = sorted(sentences, key=lambda s: -_score_sentence(s, query_kw))
            top = ranked[: min(4, len(ranked))]
            text = " ".join(top)
            text = (
                f"{text}\n\n[Generated by offline mock provider — extractive synthesis of the "
                f"supplied context. Configure LLM_PROVIDER=openai for full generative reasoning.]"
            )
        return LLMResult(text=text, prompt_tokens=len(user_prompt.split()), completion_tokens=len(text.split()), model=self.name)

    def generate_structured(
        self, system_prompt: str, user_prompt: str, schema: dict[str, Any], *, temperature: float = 0.0
    ) -> StructuredResult:
        properties = schema.get("properties", {})
        sentences = _sentences(user_prompt)
        data: dict[str, Any] = {}
        for i, key in enumerate(properties.keys()):
            prop_type = properties[key].get("type", "string")
            if prop_type == "array":
                data[key] = sentences[i : i + 2] if sentences else []
            elif prop_type == "number":
                data[key] = 0.0
            else:
                data[key] = sentences[i] if i < len(sentences) else "Not enough information extracted."
        return StructuredResult(data=data, model=self.name)

    def embed(self, texts: list[str]) -> EmbeddingResult:
        vectors = [self._deterministic_vector(t) for t in texts]
        return EmbeddingResult(vectors=vectors, model=self.name, dim=self.embedding_dim)

    def _deterministic_vector(self, text: str) -> list[float]:
        """Hash-based bag-of-words embedding: deterministic, no ML dependency,
        but still reflects lexical overlap so cosine similarity is meaningful
        for retrieval in development/testing."""
        vec = [0.0] * self.embedding_dim
        for word in _keywords(text):
            h = int(hashlib.md5(word.encode()).hexdigest(), 16)
            idx = h % self.embedding_dim
            sign = 1.0 if (h // self.embedding_dim) % 2 == 0 else -1.0
            vec[idx] += sign
        norm = sum(v * v for v in vec) ** 0.5
        if norm > 0:
            vec = [v / norm for v in vec]
        return vec
